--AUTOINCREMENT EMPLEADO

CREATE SEQUENCE SEQ_EMP
START WITH 1
INCREMENT BY 1;

CREATE TRIGGER TRIG_EMP
BEFORE INSERT ON EMPLEADO
FOR EACH ROW
BEGIN
SELECT SEQ_EMP.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

--AUTOINCREMENT EMPRESA
-- PARA TABLA EMPRESA...
CREATE SEQUENCE SQ_EMPRESA
START WITH 1
INCREMENT BY 1;


CREATE OR REPLACE TRIGGER TRIG_EMPRESA
BEFORE INSERT ON EMPRESA
FOR EACH ROW
 WHEN (new.ID IS NULL) 
BEGIN
  SELECT SQ_EMPRESA.NEXTVAL 
  INTO :new.ID
  FROM dual;
END;

--AUTOINCREMENT FAMILIA DE PRODUCTO

CREATE SEQUENCE SEQ_FAM
START WITH 1
INCREMENT BY 1;

CREATE TRIGGER TRIG_FAM
BEFORE INSERT ON FAMILIA_PRODUCTO
FOR EACH ROW
BEGIN
SELECT SEQ_FAM.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

--AUTOINCREMENT ORDEN DE PEDIDO

CREATE SEQUENCE SEQ_ORDEN_P
START WITH 1
INCREMENT BY 1;

CREATE TRIGGER TRIG_ORDEN_P
BEFORE INSERT ON ORDEN_PEDIDO
FOR EACH ROW
BEGIN
SELECT SEQ_ORDEN_P.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

--AUTOINCREMENT PRODUCTO

CREATE SEQUENCE SEQ_PROD
START WITH 1
INCREMENT BY 1;

CREATE TRIGGER TRIG_PROD
BEFORE INSERT ON PRODUCTO
FOR EACH ROW
BEGIN
SELECT SEQ_PROD.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

--AUTOINCREMENT PROVEEDOR

CREATE SEQUENCE SEQ_PROV
START WITH 1
INCREMENT BY 1;

CREATE TRIGGER TRIG_PROV
BEFORE INSERT ON PROVEEDOR
FOR EACH ROW
BEGIN
SELECT SEQ_PROV.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

--AUTOINCREMENT RUBRO

CREATE SEQUENCE SEQ_RUBRO
START WITH 1
INCREMENT BY 1;

CREATE TRIGGER TRIG_RUBRO
BEFORE INSERT ON RUBRO
FOR EACH ROW
BEGIN
SELECT SEQ_RUBRO.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

--AUTOINCREMENT TIPO_PRODUCTO

CREATE SEQUENCE SEQ_TIPO_P
START WITH 1
INCREMENT BY 1;

CREATE TRIGGER TRIG_TIPO_P
BEFORE INSERT ON TIPO_PRODUCTO
FOR EACH ROW
BEGIN
SELECT SEQ_TIPO_P.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

--AUTOINCREMENT TRABAJADOR

CREATE SEQUENCE SEQ_TRAB
START WITH 1
INCREMENT BY 1;

CREATE TRIGGER TRIG_TRAB
BEFORE INSERT ON TRABAJADOR
FOR EACH ROW
BEGIN
SELECT SEQ_TRAB.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

--AUTOINCREMENT USUARIO

CREATE SEQUENCE SEQ_USU
START WITH 1
INCREMENT BY 1;

CREATE TRIGGER TRIG_USU
BEFORE INSERT ON USUARIO
FOR EACH ROW
BEGIN
SELECT SEQ_USU.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
