//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostalWeb.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public CLIENTE()
        {
            this.EMPRESA = new HashSet<EMPRESA>();
        }
    
        public int ID_CLIENTE { get; set; }
        public string RUT_EMPRESA { get; set; }
        public string NOMBRE_CLIENTE { get; set; }
        public string TELEFONO_CLIENTE { get; set; }
        public string CORREO_CLIENTE { get; set; }
        public string USUARIO_CLIENTE { get; set; }
        public string CONTRASENA_CLIENTE { get; set; }
        public int ID_USUARIO { get; set; }
        public int PERFIL_CLIENTE { get; set; }
    
        public virtual ICollection<EMPRESA> EMPRESA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
