//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostalWeb.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMEDOR
    {
        public int ID_COMEDOR { get; set; }
        public string NOMBRE { get; set; }
        public int ID_SERVICIO { get; set; }
        public int ID_ORDEN { get; set; }
    
        public virtual ORDEN_DE_COMPRA ORDEN_DE_COMPRA { get; set; }
        public virtual TIPO_SERVICIO TIPO_SERVICIO { get; set; }
    }
}
