//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostalWeb.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        public EMPLEADO()
        {
            this.ORDEN_DE_PEDIDO = new HashSet<ORDEN_DE_PEDIDO>();
        }
    
        public int ID_EMPLEADO { get; set; }
        public string RUT_EMPLEADO { get; set; }
        public string NOMBRES_EMPLEADO { get; set; }
        public string APELLIDOS_EMPLEADO { get; set; }
        public string TELEFONO_EMPLEADO { get; set; }
        public int ESTADO_EMPLEADO { get; set; }
        public string CORREO_EMPLEADO { get; set; }
        public int PERFIL_EMPLEADO { get; set; }
        public int ID_USUARIO { get; set; }
        public string USUARIO_USUARIO { get; set; }
    
        public virtual ICollection<ORDEN_DE_PEDIDO> ORDEN_DE_PEDIDO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
