//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostalWeb.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        public int ID { get; set; }
        public int RUT { get; set; }
        public string DV { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public string CARGO { get; set; }
        public string TELEFONO { get; set; }
        public string CORREO { get; set; }
        public int ESTADO_ID { get; set; }
        public Nullable<int> USUARIO_ID { get; set; }
    
        public virtual ESTADO_EMPLEADO ESTADO_EMPLEADO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
