//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostalWeb.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPRESA
    {
        public EMPRESA()
        {
            this.TRABAJADOR = new HashSet<TRABAJADOR>();
        }
    
        public int ID { get; set; }
        public int RUT { get; set; }
        public string DV { get; set; }
        public string NOMBRE { get; set; }
        public string GIRO { get; set; }
        public string DIRECCION { get; set; }
    
        public virtual ICollection<TRABAJADOR> TRABAJADOR { get; set; }
    }
}
