//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostalWeb.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class HABITACION
    {
        public int ID_HABITACION { get; set; }
        public int NUMERO_HABITACION { get; set; }
        public int DISPONIBILIDAD_HABITACION { get; set; }
        public string ACCESORIOS_HABITACION { get; set; }
        public int ID_TIPO { get; set; }
        public int ID_ORDEN { get; set; }
        public int ID_ESTADO { get; set; }
    
        public virtual ESTADO_HABITACION ESTADO_HABITACION { get; set; }
        public virtual ORDEN_DE_COMPRA ORDEN_DE_COMPRA { get; set; }
        public virtual TIPO_HABITACION TIPO_HABITACION { get; set; }
    }
}
