//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostalWeb.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class HUESPED
    {
        public int ID_FICHA { get; set; }
        public System.DateTime FECHA_INGRESO { get; set; }
        public System.DateTime FECHA_SALIDA { get; set; }
        public string ESTADO { get; set; }
    }
}
