//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostalWeb.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class MINUTA_PLATO
    {
        public int ID { get; set; }
        public int MINUTA_ID { get; set; }
        public int PLATO_ID { get; set; }
        public Nullable<System.DateTime> HORA { get; set; }
    
        public virtual MINUTA MINUTA { get; set; }
        public virtual PLATO PLATO { get; set; }
    }
}
