//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostalWeb.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class MINUTA
    {
        public MINUTA()
        {
            this.CALENDARIO_MINUTA = new HashSet<CALENDARIO_MINUTA>();
        }
    
        public int ID_MINUTA { get; set; }
        public int ID_CALENDARIO { get; set; }
        public int ID_SERVICIO { get; set; }
    
        public virtual ICollection<CALENDARIO_MINUTA> CALENDARIO_MINUTA { get; set; }
        public virtual DETALLE_MINUTA DETALLE_MINUTA { get; set; }
        public virtual TIPO_SERVICIO TIPO_SERVICIO { get; set; }
    }
}
