//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostalWeb.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEN_PEDIDO
    {
        public int ID { get; set; }
        public int PROVEEDOR_ID { get; set; }
        public int PRODUCTO_ID { get; set; }
        public string DETALLE { get; set; }
        public int EMPLEADO_ID { get; set; }
        public int TOTAL { get; set; }
        public Nullable<int> ESTADO_ORDEN_ID { get; set; }
    
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual ESTADO_ORDEN ESTADO_ORDEN { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
    }
}
