//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostalWeb.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEN_DE_COMPRA
    {
        public ORDEN_DE_COMPRA()
        {
            this.COMEDOR = new HashSet<COMEDOR>();
            this.HABITACION = new HashSet<HABITACION>();
        }
    
        public int ID_ORDEN { get; set; }
        public System.DateTime FECHA_ORDEN { get; set; }
        public int ID_FACTURA { get; set; }
        public string DETALLE_ORDEN { get; set; }
        public Nullable<int> PRECIO_ORDEN { get; set; }
        public string RUT_TRABAJADOR { get; set; }
    
        public virtual ICollection<COMEDOR> COMEDOR { get; set; }
        public virtual FACTURA FACTURA { get; set; }
        public virtual ICollection<HABITACION> HABITACION { get; set; }
        public virtual TRABAJADOR TRABAJADOR { get; set; }
    }
}
