//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostalWeb.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVEEDOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROVEEDOR()
        {
            this.STOCK = new HashSet<STOCK>();
        }
    
        public int ID_PROVEEDOR { get; set; }
        public string RUT_PROVEEDOR { get; set; }
        public string DV_PROVEEDOR { get; set; }
        public string NOMBRES_PROVEEDOR { get; set; }
        public string APELLIDOS_PROVEEDOR { get; set; }
        public string TELEFONO_PROVEEDOR { get; set; }
        public string CORREO_PROVEEDOR { get; set; }
        public int ID_RUBRO { get; set; }
        public int ID_USUARIO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOCK> STOCK { get; set; }
        public virtual RUBRO RUBRO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
