//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostalWeb.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRABAJADOR
    {
        public TRABAJADOR()
        {
            this.ORDEN_DE_COMPRA = new HashSet<ORDEN_DE_COMPRA>();
        }
    
        public string RUT_TRABAJADOR { get; set; }
        public string DV_TRABAJADOR { get; set; }
        public string NOMBRE_TRABAJADOR { get; set; }
        public string APELLIDO_TRABAJADOR { get; set; }
        public string TELEFONO { get; set; }
        public int ID_EMPRESA { get; set; }
    
        public virtual EMPRESA EMPRESA { get; set; }
        public virtual ICollection<ORDEN_DE_COMPRA> ORDEN_DE_COMPRA { get; set; }
    }
}
